uploads = []
generated = []

[[outputs]]
id = "-F62xbFyYm628nPKCL9h9"
uri = "file://ShelterApp_Ready.zip"
type = "unspecified"
title = "ShelterApp Fixed - Free Plan Ready (2.9MB)"

[[outputs]]
id = "XWMOItCj4kp4QWNPvJRY1"
uri = "file://codemagic.yaml"
type = "unspecified"
title = "codemagic.yaml - Fixed for NowInAndroid"
